version: "3"
services:
  dnam-mainserver:
    image: se-artif-prd.infinera.com/enlighten/tnmserver:30.0.0
    container_name: dnam-mainserver
    environment:
      - "JAVA_OPTS=-Drest.server.enabled=true -Ddb.host=tnmdb -Damqp.host=rabbitmq"
    depends_on:
      - tnmdb
      - rabbitmq
    links:
      - tnmdb
      - rabbitmq
  tnmdb:
    image: mariadb:10.1
    container_name: tnmdb
    environment:
      MYSQL_USER: tnmuser
      MYSQL_PASSWORD: d4NaZ9j3k
      MYSQL_DATABASE: tnmdb
      MYSQL_ROOT_PASSWORD: root
  rabbitmq:
    image: se-artif-prd.infinera.com/enlighten/rabbitmq:3.6.14
    container_name: rabbitmq
  node1:
    image: se-artif-prd.infinera.com/tm3k/trunk-hostenv:29.0
    container_name: node1
    environment:
      - DEMO=true -nosim
    privileged: true
    ports:
      - 80
  node2:
    image: se-artif-prd.infinera.com/tm3k/trunk-hostenv:29.0
    container_name: node2
    environment:
      - DEMO=true -nosim
    privileged: true
