version: "3"
services:
  dnam-functional-acceptance-test:
    image: "dnam-functional-acceptance-test:${VERSION}"
    build: .
    container_name: dnam-acceptance-test
    depends_on:
      - dnam-mainserver
    links:
        - dnam-mainserver
    entrypoint: ./wait-for-it.sh
    command: "dnam-mainserver:1099 --timeout=300 --strict -- ./run-dnam-functional-acceptance-tests.sh ${TESTS_TO_RUN}"