#!/usr/bin/env bash


trim_leading_and_ending_double_quotes() {
    echo $(sed -e 's/^"//' -e 's/"$//' <<<"${1}")
}
# Trims string before rightmost dot. If string without dot the string will
# be returned unmodified
# /wsserver_main/29.1.0.b8e0d1c --> b8e0d1c
# /wsserver_main/27.0.2 --> 2
trim_string_before_rightmost_dot() {
    echo "${1##*.}"
}

# Checks if string length is >= 7, which it should be if the directory
# is named using git hash
# TODO: Add expected length as input parameter
string_has_expected_length() {
    [ ${#1} -ge 7 ]
}

is_alpha_numeric() {
    [[ "${1}" =~ ^[A-Za-z0-9]*$ ]]
}

is_numeric() {
    [[ ${1} =~ ^[0-9]+$ ]]
}

is_alpabetic() {
    [[ ${1} =~ ^[A-Za-z]+$ ]]
}

get_latest_deployed_dnam_version() {
    local readonly LATEST_DNAM_VERSION=$(curl -s -uadmin:admin -X GET http://tnm:8081/api/version | jq '.[] | "\(.major).\(.minor).\(.patch)"')
    echo "${LATEST_DNAM_VERSION}"
}